"""empty message

Revision ID: 442360b9d61a
Revises: cbc6fcb4b7c5
Create Date: 2025-03-21 14:32:19.819541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442360b9d61a'
down_revision = 'cbc6fcb4b7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('final',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('final',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
