"""empty message

Revision ID: 520a91ae17f7
Revises: 7f69b398d1e9
Create Date: 2025-03-25 15:52:34.053116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520a91ae17f7'
down_revision = '7f69b398d1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('event_log_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('date_time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_log')
    # ### end Alembic commands ###
