"""empty message

Revision ID: cbc6fcb4b7c5
Revises: b41f32150b94
Create Date: 2025-03-21 14:26:18.915011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc6fcb4b7c5'
down_revision = 'b41f32150b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('final', sa.String(), nullable=False),
    sa.Column('first_grading', sa.Integer(), nullable=False),
    sa.Column('second_grading', sa.Integer(), nullable=False),
    sa.Column('third_grading', sa.Integer(), nullable=False),
    sa.Column('fourth_grading', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    # ### end Alembic commands ###
